a = input('Digite algo: ')
print('O tipo primitivo deste valor é ', type(a))
print('Só tem espaços?',a.isspace())
print('É um número?',a.isnumeric())
print('Tem letras?',a.isalpha())
print('Tem letras e números?',a.isalnum())
print('Está em maiúsculas?',a.isupper())
print('Está em minúsculas?',a.islower())
print('Está capitalizada?',a.istitle())
